#!/usr/bin/env python3
# Exact finite-field degree-3 certificate for the quadratic ideal of the
# HPP Y(3,6) canonical-form map.  This implements one degree of the F4/
# Macaulay computation, using a deterministic random linear projection only
# to certify independence: rank 706 after projection implies rank >=706
# before projection.
import gc,itertools,json,os,random,struct,sys,time,hashlib
import numpy as np
from flint import fmpz_mod_ctx,fmpz_mod_mat
sys.path.insert(0,os.getcwd())
import y36_cubic_sieve as y
p=1000003; seed=260728368; projdim=706; ctx=fmpz_mod_ctx(p); rng=random.Random(seed); t=time.time()
print('expected: ~30s interpolation, then projected confluence search; target residual rank 706',flush=True)
# Coordinate selection and exact quadratic interpolation.
coord=y.pivot_columns(fmpz_mod_mat([y.random_point(rng,p) for _ in range(170)],ctx)); assert len(coord)==150
Y=[]
for z in range(1720):
 f=y.random_point(rng,p);Y.append([f[i] for i in coord])
perm=list(reversed(range(150)))
logical=y.grevlex_degree2_increasing(150)
mons=[tuple(sorted((perm[i],perm[j]))) for i,j in logical]
col={m:i for i,m in enumerate(mons)}
Q=fmpz_mod_mat([[(r[i]*r[j])%p for i,j in mons] for r in Y],ctx); del Y
R,rank=Q.rref();del Q;gc.collect();assert rank==1720
pivs=[];last=-1
for row in range(rank):
 for j in range(last+1,R.ncols()):
  if int(R[row,j]):pivs.append(j);last=j;break
assert len(pivs)==1720
P=set(pivs); prow={j:i for i,j in enumerate(pivs)}
# Sparse rewrite rules monomial -> [(coefficient, pivot quadratic monomial)].
rules={}; nnz=0; rulehash=hashlib.sha256()
for j,m in enumerate(mons):
 if j in P: continue
 rr=[]
 # Column rank profile means only pivot columns preceding j occur.
 for i,pj in enumerate(pivs):
  a=int(R[i,j])
  if a:
   rr.append((a,mons[pj])); rulehash.update(struct.pack('<III',j,i,a))
 rules[m]=rr;nnz+=len(rr)
del R;gc.collect()
print(f'quadratic_rank={rank} rules={len(rules)} rule_nnz={nnz} elapsed={time.time()-t:.1f}',flush=True)
# Standard cubics for the monomial ideal generated by quadratic leading terms.
def pair_rules(c):
 i,j,k=c
 ans=[]
 for q,r in [((i,j),k),((i,k),j),((j,k),i)]:
  q=tuple(sorted(q)); item=(q,r)
  if q in rules and item not in ans: ans.append(item)
 return ans
allcub=itertools.combinations_with_replacement(range(150),3)
standard=[c for c in allcub if not pair_rules(c)]
assert len(standard)==8582
sindex={c:i for i,c in enumerate(standard)}
# Explicit deterministic projection F_p^8582 -> F_p^706.
ng=np.random.default_rng(314159265)
Proj=ng.integers(0,p,size=(len(standard),projdim),dtype=np.uint64)
# Hash the projection in canonical little-endian uint32 representation.
ph=hashlib.sha256(Proj.astype('<u4').tobytes()).hexdigest()
cache={c:Proj[i].copy() for i,c in enumerate(standard)}
visiting=set()
def add_scaled(out,a,v):
 out += np.uint64(a)*v

def rewrite(c,qr):
 q,rem=qr; out=np.zeros(projdim,dtype=np.uint64); terms=rules[q]
 # Rule tails are sparse (about 50 terms on average); reduce modulo p in
 # chunks to stay far below uint64 overflow.
 for z,(a,b) in enumerate(terms):
  cc=tuple(sorted((rem,b[0],b[1])))
  add_scaled(out,a,nf(cc))
  if z%32==31: out%=p
 out%=p; return out

def nf(c):
 v=cache.get(c)
 if v is not None:return v
 if c in visiting:raise RuntimeError('non-terminating rewrite')
 visiting.add(c); rr=pair_rules(c); assert rr
 v=rewrite(c,rr[0]);cache[c]=v;visiting.remove(c);return v
# Online row echelon for projected confluence residuals.
ebasis={} ; tested=0; accepted=[]
# Prefer cubics in reverse physical lex; the result is independent of scan order.
for c in itertools.combinations_with_replacement(range(149,-1,-1),3):
 c=tuple(sorted(c)); rr=pair_rules(c)
 if len(rr)<2: continue
 base=nf(c)
 for alt in rr[1:]:
  v=(rewrite(c,alt).astype(np.int64)-base.astype(np.int64))%p
  v=v.astype(np.uint64);tested+=1
  for k,b in list(ebasis.items()):
   a=int(v[k])
   if a: v=(v + np.uint64(p-a)*b)%p
  nz=np.flatnonzero(v)
  if len(nz):
   k=int(nz[0]); inv=pow(int(v[k]),p-2,p);v=(v*np.uint64(inv))%p;ebasis[k]=v;accepted.append((c,alt,k))
   if len(ebasis)%50==0: print(f'residual_rank={len(ebasis)} tested={tested} cache={len(cache)} elapsed={time.time()-t:.1f}',flush=True)
   if len(ebasis)==projdim:break
 if len(ebasis)==projdim:break
 if tested%1000==0: print(f'tested={tested} residual_rank={len(ebasis)} cache={len(cache)} elapsed={time.time()-t:.1f}',flush=True)
ah=hashlib.sha256()
for c,alt,k in accepted: ah.update(struct.pack('<IIIIII',c[0],c[1],c[2],alt[0][0],alt[0][1],alt[1]));ah.update(struct.pack('<I',k))
bh=hashlib.sha256()
for k in sorted(ebasis): bh.update(struct.pack('<I',k));bh.update(ebasis[k].astype('<u4').tobytes())
res={'prime':p,'seed':seed,'coordinate_indices_sha256':y.sha_ints(coord),'variable_permutation_sha256':y.sha_ints(perm),'quadratic_rank':rank,'quadratic_kernel_dimension':11325-rank,'quadratic_pivot_indices_sha256':y.sha_ints(pivs),'quadratic_rule_nnz':nnz,'quadratic_rules_sha256':rulehash.hexdigest(),'standard_cubics_after_quadratic_leads':len(standard),'projection_dimension':projdim,'projection_sha256':ph,'confluence_residual_rank':len(ebasis),'accepted_residuals_sha256':ah.hexdigest(),'projected_echelon_basis_sha256':bh.hexdigest(),'residuals_tested':tested,'normal_forms_cached':len(cache),'certified_cubic_ideal_rank':573800-len(standard)+len(ebasis),'target':565924}
print(json.dumps(res,indent=2,sort_keys=True),flush=True)
open('y36_cubic_rank_result.json','w').write(json.dumps(res,indent=2,sort_keys=True))
if len(ebasis)!=projdim:sys.exit(2)
